title: Trevor Malard
description: Trevor Malard, Tokyo-based digital creative. Web design and Video production.

links:
  - code
  - video
  - contact

# F-u scraping bots 😡
social:
  email: Y29udGFjdEB0bWFsYXJkLmpw
  vimeo: https://vimeo.com/tmalard
  github: https://github.com/tmalard

collections:
  open_source_contributions:
    output: true
    permalink: /open-source/:name
  closed_source_contributions:
    output: true
    permalink: /closed-source/:name
  archived_contributions:
    output: true
    permalink: /archived/:name
  video_content:
    output: true
    permalink: /video/:name

fallbacks:
  splash_video: https://raw.githubusercontent.com/tmalard/tmalard.github.io/source/assets/bg.mp4

static_files:
  splash_video: /assets/bg.mp4

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
