title: Trevor Malard
description: Trevor Malard, Tokyo-based digital creative. Web design and Video production.

links:
  - code
  - video
  - contact

# F-u scraping bots 😡
social:
  email: Y29udGFjdEB0bWFsYXJkLmpw
  vimeo: https://vimeo.com/tmalard
  github: https://github.com/fire-pls
